accounts/urls.py
from django.urls import path
from accounts.views import user_login, user_logout, signup

urlpatterns = [
    path("signup/", signup, name="signup"),
    path("logout/", user_logout, name="logout"),
    path("login/", user_login, name="login"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect


def redirect_to_receipt_list(request):
    return redirect("home")


urlpatterns = [
    path("accounts/", include("accounts.urls")),
    path("", redirect_to_receipt_list),
    path("receipts/", include("receipts.urls")),
    path("admin/", admin.site.urls),
]

receipts/urls.py
from django.urls import path
from receipts.views import (
    create_account,
    receipt_list,
    create_receipt,
    expense_category_list,
    account_list,
    create_expense_category,
)


urlpatterns = [
    path("accounts/create/", create_account, name="create_account"),
    path(
        "categories/create/",
        create_expense_category,
        name="create_expense_category",
    ),
    path("categories/", expense_category_list, name="expense_category_list"),
    path("accounts/", account_list, name="account_list"),
    path("create/", create_receipt, name="create_receipt"),
    path("", receipt_list, name="home"),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        User, related_name="categories", on_delete=models.CASCADE
    )


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        User, related_name="accounts", on_delete=models.CASCADE
    )


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    tax = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateTimeField()
    purchaser = models.ForeignKey(
        User, related_name="receipts", on_delete=models.CASCADE
    )
    category = models.ForeignKey(
        ExpenseCategory, related_name="receipts", on_delete=models.CASCADE
    )
    account = models.ForeignKey(
        Account, related_name="receipts", on_delete=models.CASCADE, null=True
    )

accounts/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(max_length=150, widget=forms.PasswordInput)


class SignUpForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(
        max_length=150,
        widget=forms.PasswordInput,
    )
    password_confirmation = forms.CharField(
        max_length=150,
        widget=forms.PasswordInput,
    )

receipts/forms.py
from django.forms import ModelForm
from receipts.models import Receipt, ExpenseCategory, Account


class ReceiptForm(ModelForm):
    class Meta:
        model = Receipt
        fields = [
            "vendor",
            "total",
            "tax",
            "date",
            "category",
            "account",
        ]


class ExpenseCategoryForm(ModelForm):
    class Meta:
        model = ExpenseCategory
        fields = [
            "name",
        ]


class AccountForm(ModelForm):
    class Meta:
        model = Account
        fields = [
            "name",
            "number",
        ]

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from accounts.forms import LoginForm, SignUpForm


# Create your views here.
def user_login(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]

            user = authenticate(
                request,
                username=username,
                password=password,
            )
            if user is not None:
                login(request, user)
                return redirect("home")
    else:
        form = LoginForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/login.html", context)


def user_logout(request):
    logout(request)
    return redirect("login")


def signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            password_confirmation = form.cleaned_data["password_confirmation"]

            if password == password_confirmation:
                user = User.objects.create_user(
                    username,
                    password=password,
                )
                login(request, user)
                return redirect("home")
            else:
                form.add_error("password", "Passwords do not match")
    else:
        form = SignUpForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/signup.html", context)

receipts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from receipts.models import Receipt, ExpenseCategory, Account
from receipts.forms import ReceiptForm, ExpenseCategoryForm, AccountForm


# Create your views here.
@login_required
def receipt_list(request):
    receipts = Receipt.objects.filter(purchaser=request.user)
    context = {
        "receipt_list": receipts,
    }
    return render(request, "receipts/receipt_list.html", context)


@login_required
def create_receipt(request):
    if request.method == "POST":
        form = ReceiptForm(request.POST)
        if form.is_valid():
            receipt = form.save(False)
            receipt.purchaser = request.user
            receipt.save()
            return redirect("home")
    else:
        form = ReceiptForm()
    context = {
        "form": form,
    }
    return render(request, "receipts/create_receipt.html", context)


@login_required
def expense_category_list(request):
    categories = ExpenseCategory.objects.filter(owner=request.user)
    context = {
        "categories": categories,
    }
    return render(request, "receipts/expense_category_list.html", context)


@login_required
def account_list(request):
    accounts = Account.objects.filter(owner=request.user)
    context = {
        "accounts": accounts,
    }
    return render(request, "receipts/account_list.html", context)


@login_required
def create_expense_category(request):
    if request.method == "POST":
        form = ExpenseCategoryForm(request.POST)
        if form.is_valid():
            new_category = form.save(False)
            new_category.owner = request.user
            new_category.save()
            return redirect("expense_category_list")
    else:
        form = ExpenseCategoryForm()
    context = {"form": form}
    return render(request, "receipts/create_expense_category.html", context)


@login_required
def create_account(request):
    if request.method == "POST":
        form = AccountForm(request.POST)
        if form.is_valid():
            account = form.save(False)
            account.owner = request.user
            account.save()
            return redirect("account_list")
    else:
        form = AccountForm()
    context = {"form": form}
    return render(request, "receipts/create_account.html", context)

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        <main>
            <div>
                <h1>Login</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button>Login</button>
                </form>
            </div>
        </main>
    </body>
</html>

accounts/templates/accounts/signup.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        <main>
            <div>
                <h1>Signup</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button>Signup</button>
                </form>
            </div>
        </main>
    </body>
</html>

receipts/templates/receipts/account_list.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        {% if user.is_authenticated %}
            <nav>
                <ul>
                    <li>
                        <a href="{% url 'home' %}">Receipt List</a>
                    </li>
                    <li>
                        <a href="{% url 'create_receipt' %}">Create Receipt</a>
                    </li>
                    <li>
                        <a href="{% url 'expense_category_list' %}">Expense Categories</a>
                    </li>
                    <li>
                        <a href="{% url 'create_expense_category' %}">Create Expense Category</a>
                    </li>
                    <li>
                        <a href="{% url 'account_list' %}">Accounts</a>
                    </li>
                    <li>
                        <a href="{% url 'create_account' %}">Create Account</a>
                    </li>
                </ul>
            </nav>
        {% endif %}
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Number</th>
                    <th>Number of receipts</th>
                </tr>
            </thead>
            <tbody>
                {% for account in accounts %}
                    <tr>
                        <td>{{ account.name }}</td>
                        <td>{{ account.number }}</td>
                        <td>{{ account.receipt_set.count }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </body>
</html>

receipts/templates/receipts/create_account.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        {% if user.is_authenticated %}
            <nav>
                <ul>
                    <li>
                        <a href="{% url 'home' %}">Receipt List</a>
                    </li>
                    <li>
                        <a href="{% url 'create_receipt' %}">Create Receipt</a>
                    </li>
                    <li>
                        <a href="{% url 'expense_category_list' %}">Expense Categories</a>
                    </li>
                    <li>
                        <a href="{% url 'create_expense_category' %}">Create Expense Category</a>
                    </li>
                    <li>
                        <a href="{% url 'account_list' %}">Accounts</a>
                    </li>
                    <li>
                        <a href="{% url 'create_account' %}">Create Account</a>
                    </li>
                </ul>
            </nav>
        {% endif %}
        <main>
            <div>
                <h1>Create Account</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button>Create</button>
                </form>
            </div>
        </main>
    </body>
</html>

receipts/templates/receipts/create_expense_category.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        {% if user.is_authenticated %}
            <nav>
                <ul>
                    <li>
                        <a href="{% url 'home' %}">Receipt List</a>
                    </li>
                    <li>
                        <a href="{% url 'create_receipt' %}">Create Receipt</a>
                    </li>
                    <li>
                        <a href="{% url 'expense_category_list' %}">Expense Categories</a>
                    </li>
                    <li>
                        <a href="{% url 'create_expense_category' %}">Create Expense Category</a>
                    </li>
                    <li>
                        <a href="{% url 'account_list' %}">Accounts</a>
                    </li>
                    <li>
                        <a href="{% url 'create_account' %}">Create Account</a>
                    </li>
                </ul>
            </nav>
        {% endif %}
        <main>
            <div>
                <h1>Create Category</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button>Create</button>
                </form>
            </div>
        </main>
    </body>
</html>

receipts/templates/receipts/create_receipt.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        {% if user.is_authenticated %}
            <nav>
                <ul>
                    <li>
                        <a href="{% url 'home' %}">Receipt List</a>
                    </li>
                    <li>
                        <a href="{% url 'create_receipt' %}">Create Receipt</a>
                    </li>
                    <li>
                        <a href="{% url 'expense_category_list' %}">Expense Categories</a>
                    </li>
                    <li>
                        <a href="{% url 'create_expense_category' %}">Create Expense Category</a>
                    </li>
                    <li>
                        <a href="{% url 'account_list' %}">Accounts</a>
                    </li>
                    <li>
                        <a href="{% url 'create_account' %}">Create Account</a>
                    </li>
                </ul>
            </nav>
        {% endif %}
        <main>
            <div>
                <h1>Create Receipt</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button>Create</button>
                </form>
            </div>
        </main>
    </body>
</html>

receipts/templates/receipts/expense_category_list.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        {% if user.is_authenticated %}
            <nav>
                <ul>
                    <li>
                        <a href="{% url 'home' %}">Receipt List</a>
                    </li>
                    <li>
                        <a href="{% url 'create_receipt' %}">Create Receipt</a>
                    </li>
                    <li>
                        <a href="{% url 'expense_category_list' %}">Expense Categories</a>
                    </li>
                    <li>
                        <a href="{% url 'create_expense_category' %}">Create Expense Category</a>
                    </li>
                    <li>
                        <a href="{% url 'account_list' %}">Accounts</a>
                    </li>
                    <li>
                        <a href="{% url 'create_account' %}">Create Account</a>
                    </li>
                </ul>
            </nav>
        {% endif %}
        <main>
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Number of receipts</th>
                    </tr>
                </thead>
                <tbody>
                    {% for category in categories %}
                        <tr>
                            <td>{{ category.name }}</td>
                            <td>
                                {{ category.receipt_set.count }}
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </main>
        </body>
    </html>

receipts/templates/receipts/receipt_list.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        {% if user.is_authenticated %}
            <nav>
                <ul>
                    <li>
                        <a href="{% url 'home' %}">Receipt List</a>
                    </li>
                    <li>
                        <a href="{% url 'create_receipt' %}">Create Receipt</a>
                    </li>
                    <li>
                        <a href="{% url 'expense_category_list' %}">Expense Categories</a>
                    </li>
                    <li>
                        <a href="{% url 'create_expense_category' %}">Create Expense Category</a>
                    </li>
                    <li>
                        <a href="{% url 'account_list' %}">Accounts</a>
                    </li>
                    <li>
                        <a href="{% url 'create_account' %}">Create Account</a>
                    </li>
                </ul>
            </nav>
        {% endif %}
        <header>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'logout' %}">Logout</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url 'signup' %}">Sign Up</a>
                        </li>
                        <li>
                            <a href="{% url 'login' %}">Login</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <main>
            <h1>My Receipts</h1>
            <table>
                <thead>
                    <tr>
                        <th>Vendor</th>
                        <th>Total</th>
                        <th>Tax</th>
                        <th>Date</th>
                        <th>Category</th>
                        <th>Account</th>
                    </tr>
                </thead>
                <tbody>
                    {% for receipt in receipt_list %}
                        <tr>
                            <td>{{ receipt.vendor }}</td>
                            <td>{{ receipt.total }}</td>
                            <td>{{ receipt.tax }}</td>
                            <td>{{ receipt.date|date:"m/d/y" }}</td>
                            <td>{{ receipt.category.name }}</td>
                            <td>{{ receipt.account.name }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </main>
    </body>
</html>